puts "Canibal".object_id
puts "Canibal".object_id
puts "Canibal".object_id
puts "Canibal".object_id
puts "===================="
puts :Canibal.object_id
puts :Canibal.object_id
puts :Canibal.object_id
puts :Canibal.object_id
puts :Canibal.object_id
